<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dishextension"
 *
 * Auto generated by Extension Builder 2018-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'DishExtension',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Aishwarya Bhosale',
    'author_email' => 'aishwarya.bhosale@hof-university.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
